# Generated by Django 5.2.7 on 2025-11-04 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('rebalance', 'Rebalance'), ('manual', 'Manual Trade')], max_length=20)),
                ('dry_run', models.BooleanField(default=True)),
                ('trade_data', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trade histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('next_run_time', models.DateTimeField(blank=True, null=True)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('last_portfolio', models.JSONField(blank=True, default=dict)),
                ('last_rebalance_result', models.JSONField(blank=True, default=dict)),
                ('dry_run_mode', models.BooleanField(default=True, help_text='Test mode (no real trades)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binance_api_key_encrypted', models.TextField(blank=True, null=True)),
                ('binance_api_secret_encrypted', models.TextField(blank=True, null=True)),
                ('cmc_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('default_interval', models.IntegerField(default=3600, help_text='Default rebalance interval in seconds')),
                ('auto_rebalance', models.BooleanField(default=False, help_text='Enable automatic rebalancing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TraderSettings',
        ),
    ]
