# Generated by Django 5.2.7 on 2025-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tradehistory_tradersession_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='index_type',
            field=models.CharField(choices=[('top2', 'Top 2 (BTC + ETH)'), ('top5', 'Top 5'), ('top10', 'Top 10'), ('top20', 'Top 20 (Full CMC20)')], default='top2', help_text='Index distribution strategy', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_customer_id',
            field=models.CharField(blank=True, help_text='Customer ID from payment provider', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_provider',
            field=models.CharField(blank=True, help_text='e.g., stripe, paypal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_subscription_id',
            field=models.CharField(blank=True, help_text='Subscription ID from payment provider', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, help_text='When subscription expires', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, help_text='When subscription started', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free Trial'), ('active', 'Active Subscription'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='free', help_text='Current subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='When trial expires', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_used',
            field=models.BooleanField(default=False, help_text='Has user used their free trial?'),
        ),
    ]
