# Generated by Django 5.2.7 on 2025-11-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile_index_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='index_base',
            field=models.CharField(choices=[('cmc20', 'CMC20'), ('cmc100', 'CMC100')], default='cmc20', help_text='Base index to use (CMC20 or CMC100)', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='index_type',
            field=models.CharField(default='top2', help_text='Index type (top2, top5, top10, top20 for CMC20; top30-top100 for CMC100)', max_length=10),
        ),
    ]
