# Generated by Django 5.2.7 on 2025-11-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile_index_base_alter_userprofile_index_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_convert_dust',
            field=models.BooleanField(default=True, help_text='Automatically convert small balances (<$5) to target assets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cmc_index_type',
            field=models.CharField(choices=[('CMC20', 'Top 20 Index'), ('CMC100', 'Top 100 Index')], default='CMC20', help_text='Which CoinMarketCap index to follow', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='min_trade_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Minimum value for market orders (USD)', max_digits=10),
        ),
    ]
