# Generated by Django 4.2.25 on 2025-11-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userprofile_auto_convert_dust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='proxy_host',
            field=models.CharField(blank=True, help_text='Proxy server address (e.g., proxy.example.com)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='proxy_pass_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted proxy password', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='proxy_port',
            field=models.IntegerField(blank=True, help_text='Proxy server port (e.g., 1080)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='proxy_user',
            field=models.CharField(blank=True, help_text='Proxy username (if authentication required)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='use_proxy',
            field=models.BooleanField(default=False, help_text='Use SOCKS5 proxy to bypass geographic restrictions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='use_testnet',
            field=models.BooleanField(default=False, help_text='Use Binance Testnet (testnet.binance.vision) - Recommended for testing'),
        ),
    ]
