# Generated by Django 4.2.25 on 2025-11-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_userprofile_proxy_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='binance_exchange',
            field=models.CharField(choices=[('com', 'Binance.com (International)'), ('us', 'Binance.US (United States only)')], default='com', help_text='Choose your Binance exchange based on your location', max_length=10),
        ),
    ]
